### ISSUE TITLE
Performance test 

### ISSUE THREAD

**Issue by KhDenys** [vltr/xrtr#2]
Can you provide some comparison with other routers from web frameworks?

**Comment by vltr** [comment]
@KhDenys yeah, you can check that on a simple benchmark project I created [here](https://github.com/vltr/very-stupid-simple-routers-bench). I hope it helps :wink:

**Comment by vltr** [comment]
@KhDenys if the benchmark does not work (because of `hyprtr`, an internal project), you can comment it out or go back to a previous commit (sorry about that).

**Comment by KhDenys** [comment]
@vltr thank you for your reply. I did not expect such a quick answer, so I tried to write a simple test where I compared the performance with the falcon. I want to say that in my test CompiledRouter was faster. If you want, I can share my test with you.

**Comment by vltr** [comment]
@KhDenys thanks! Yeah, in some use cases, Falcon's `CompiledRouter` is indeed faster - and it's pure Python. It actually creates Python code from the routes you have defined and the _compile_ step is actually generating Python code. If you want to make a PR I would be very happy to check it :+1:
